AWSTemplateFormatVersion: 2010-09-09
Description: |
  This my Cfn template for EC2 with Security Group 
  
Resources:

  MyWebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-01c647eace872fc02
      InstanceType: t2.micro
      KeyName: firstkey
      SecurityGroupIds: 
        - !Ref MySecGrp

      Tags: 
        - Key: Name
          Value: !Sub Osvaldo ${AWS::StackName}
      UserData: 
       Fn::Base64: |
            #! /bin/bash
              sudo yum update -y
              sudo yum install httpd -y
              FOLDER="https://raw.githubusercontent.com/mahmutdemirtr/101-kittens-carousel-static-website-ec2/main/static-web"
              cd /var/www/html
              sudo wget ${FOLDER}/index.html
              sudo wget ${FOLDER}/cat0.jpg
              sudo wget ${FOLDER}/cat1.jpg
              sudo wget ${FOLDER}/cat2.jpg
              sudo wget ${FOLDER}/cat3.png
              sudo systemctl start httpd
              sudo systemctl enable httpd
     

  MySecGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ssh and http # Required
      GroupName: osvaldosecportfolio
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags: 
        - Key: env
          Value: dev
        
Outputs:
  WebSiteURL:
    Description: This output gives the URL of EC2
    Value: !Sub 
      - http://${PublicAddress}
      - PublicAddress: !GetAtt MyWebServer.PublicDnsName
 